# handlers
- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  listen: Restart haproxy

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
  listen: Restart keepalived